services:
    vincet.bootstrapform.form.type.datepicker:
        class: VinceT\BootstrapFormBundle\Form\Type\DatePickerType
        tags:
            - { name: form.type, alias: bootstrap_datepicker }
    vincet.bootstrapform.form.type.timepicker:
        class: VinceT\BootstrapFormBundle\Form\Type\TimePickerType
        tags:
            - { name: form.type, alias: bootstrap_timepicker }
    vincet.bootstrapform.form.type.datetimepicker:
        class: VinceT\BootstrapFormBundle\Form\Type\DateTimePickerType
        tags:
            - { name: form.type, alias: bootstrap_datetimepicker }
    vincet.bootstrapform.form.type.email:
        class: VinceT\BootstrapFormBundle\Form\Type\EmailType
        tags:
            - { name: form.type, alias: bootstrap_email }
    vincet.bootstrapform.form.type.percent:
        class: VinceT\BootstrapFormBundle\Form\Type\PercentType
        tags:
            - { name: form.type, alias: bootstrap_percent }